### ISSUE TITLE
批量运行py的命令有点问题

### ISSUE THREAD

**Issue by idealzxz** [zwbao/sxkouzhao#1]
批量运行py的命令有点问题，单独运行产出的py文件是可以的，但批量就不行，会找不到模块，Ps 我是mac，用的谷歌的驱动器，自己测试过驱动器没有问题，可以打开运行后自动打开百度
```
Traceback (most recent call last):
  File "0config.txt.py", line 2, in <module>
    from selenium import webdriver
ImportError: No module named selenium
```

**Comment by zwbao** [comment]
奇怪了。。代码应该是没有问题的

**Comment by idealzxz** [comment]
对的，代码是没问题的，只能一个个单独执行，批量执行就会找不到引入模块，

**Comment by zwbao** [comment]
> 对的，代码是没问题的，只能一个个单独执行，批量执行就会找不到引入模块，

我就是用这个代码批量执行的。。。应该是你那里配置的原因

**Comment by idealzxz** [comment]
好的，谢谢。应该是webdriver配置问题
